---
- name: Start hostcontrol.
  systemd:
    name: hassio-hc.service
    state: started
    daemon_reload: yes
- name: Enable and start hassio-supervisor.
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - hassio-supervisor.service